'use strict';

// The parts of a site that only matter to something that is not a person: a
// crawler deciding what exists, and a chat client deciding what a pasted link
// looks like. None of it changes what a reader sees, which is exactly why it
// rots without a test.

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { test } = require('node:test');

const ROOT = path.resolve(__dirname, '..');
const SITE = 'https://sysadmindoc.github.io/CoolSites/';
const PAGES = { 'index.html': SITE, 'collections.html': `${SITE}collections.html` };

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

test('every page says which address is the real one', () => {
  for (const [page, canonical] of Object.entries(PAGES)) {
    const match = /<link rel="canonical" href="([^"]+)">/.exec(read(page));
    assert.ok(match, `${page} has no canonical link`);
    assert.equal(match[1], canonical);
  }
});

test('a shared link renders as a card rather than a bare URL', () => {
  // Sharing is how a directory gets found. Without og:image every paste of this
  // site into Slack, Discord or Mastodon is a blue link and a shrug.
  for (const page of Object.keys(PAGES)) {
    const html = read(page);
    for (const property of ['og:image', 'og:image:width', 'og:image:height', 'og:image:alt']) {
      assert.match(html, new RegExp(`<meta property="${property}" content="[^"]+">`), `${page} is missing ${property}`);
    }
    assert.match(html, /<meta name="twitter:card" content="summary_large_image">/, `${page} still asks for the small card`);
    assert.match(html, /<meta name="twitter:image" content="[^"]+">/, `${page} is missing twitter:image`);
  }
});

test('the card the pages advertise is really there and really that size', () => {
  // A scraper that fetches og:image and gets a 404, or an image whose real
  // dimensions contradict the declared ones, renders worse than no card at all.
  for (const page of Object.keys(PAGES)) {
    const declared = /<meta property="og:image" content="([^"]+)">/.exec(read(page))[1];
    assert.ok(declared.startsWith(SITE), `${page} points og:image somewhere off-site`);
    const relative = declared.slice(SITE.length);
    const file = path.join(ROOT, relative);
    assert.ok(fs.existsSync(file), `${relative} is advertised but not in the repository`);

    const bytes = fs.readFileSync(file);
    assert.equal(bytes.subarray(0, 4).toString('hex'), '89504e47', `${relative} is not a PNG`);
    // Dimensions live in the IHDR chunk, which is always the first one.
    const width = bytes.readUInt32BE(16);
    const height = bytes.readUInt32BE(20);
    const declaredWidth = Number(/<meta property="og:image:width" content="(\d+)">/.exec(read(page))[1]);
    const declaredHeight = Number(/<meta property="og:image:height" content="(\d+)">/.exec(read(page))[1]);
    assert.equal(width, declaredWidth, `${relative} is ${width}px wide but the page claims ${declaredWidth}`);
    assert.equal(height, declaredHeight, `${relative} is ${height}px tall but the page claims ${declaredHeight}`);
  }
});

test('the sitemap lists what the site serves and nothing it does not', () => {
  const sitemap = read('sitemap.xml');
  const listed = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match => match[1]);
  assert.deepEqual(listed.sort(), Object.values(PAGES).sort(),
    'a page added or removed needs the sitemap regenerated by npm run build');
  for (const match of sitemap.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)) {
    assert.match(match[1], /^\d{4}-\d{2}-\d{2}$/, 'lastmod has to be a date a crawler can parse');
  }
});

test('robots.txt points at the sitemap and hides only local output', () => {
  const robots = read('robots.txt');
  assert.match(robots, new RegExp(`^Sitemap: ${SITE}sitemap\\.xml$`, 'm'), 'a sitemap nothing references is a file nobody reads');
  assert.match(robots, /^User-agent: \*$/m);
  // work/ is where the link-check report lands. Everything else here exists to
  // be found, so a Disallow on anything else would be a mistake.
  const disallowed = [...robots.matchAll(/^Disallow: (.+)$/gm)].map(match => match[1].trim());
  assert.deepEqual(disallowed, ['/work/']);
});
